### ISSUE TITLE
LinkedIn misses earliest backfill

### ISSUE THREAD

**Issue by corradio** [corradio/polynomial#119]
Error:

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.linkedin.com/rest/organizationalEntityShareStatistics?q=organizationalEntity&organizationalEntity=urn%3Ali%3Aorganization%3A13001719&timeIntervals.timeGranularityType=DAY&timeIntervals.timeRange.start=1451606400000&timeIntervals.timeRange.end=1683504000000&count=100
Invalid timeIntervals parameter [{timeGranularityType=DAY, timeRange={start=1451606400000, end=1683504000000}}]. Start time and end time must be less than 14 months apart.

**Comment by corradio** [comment]
When trying to backfill:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/newrelic/hooks/application_celery.py", line 99, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/autoretry.py", line 38, in run
    return task._orig_run(*args, **kwargs)
  File "/code/mainapp/tasks/__init__.py", line 106, in backfill_task
    measurements_iterator = inst.collect_past_range(
  File "/code/integrations/implementations/linkedin.py", line 184, in collect_past_range
    url = f"[https://api.linkedin.com/rest/{metric_config['endpoint']}](https://api.linkedin.com/rest/%7Bmetric_config%5B'endpoint'%5D%7D)"
KeyError: 'endpoint'
```

**Comment by corradio** [comment]
Fixed by https://github.com/corradio/polynomial/commit/290dcdfddbd53195a6c9d9a07a6ef020298a25b1
